version: '{build}'
pull_requests:
  do_not_increment_build_number: true
clone_folder: C:\gopath\src\github.com\just-install\just-install
environment:
  GOPATH: C:\gopath
  PATH: C:\gopath\bin;%PROGRAMFILES(x86)%\WiX Toolset v3.10\bin;%PATH%
  PYTHONUNBUFFERED: 1
build_script:
- cmd: build.py --skip-tests
test: off
artifacts:
- path: just-install*.exe
- path: just-install*.msi
deploy:
- provider: S3
  access_key_id: AKIAIFNMINBQKNAVYXYQ
  secret_access_key:
    secure: RXMqteyopCQHw08DqqbxQk2Jkt4AYhhbboXahuXlLtrQYJ6wpD7SbfVrxLeErSLy
  region: eu-central-1
  bucket: static.just-install.it
  folder: release/unstable
  set_public: true
  on:
    branch: master
- provider: S3
  access_key_id: AKIAIFNMINBQKNAVYXYQ
  secret_access_key:
    secure: RXMqteyopCQHw08DqqbxQk2Jkt4AYhhbboXahuXlLtrQYJ6wpD7SbfVrxLeErSLy
  region: eu-central-1
  bucket: static.just-install.it
  folder: release/stable
  set_public: true
  on:
    appveyor_repo_tag: true
